---
title: "Benchmarking estimatr"
author: "Luke Sonnet"
output:
  html_document:
    df_print: paged
vignette: |
  %\VignetteIndexEntry{Benchmarking estimatr}
  %\VignetteEngine{knitr::knitr}
  \usepackage[utf8]{inputenc}
---

This document benchmarks the speed of `lm_robust`
against other estimators. Our performance is slightly better than base R
when using classical standard errors, but most of our improvements come
when estimating robust standard errors.

The times are milliseconds and are a median over 200 runs for all but
the CR2 case, which was taken on a sample of 50 runs, using the
`microbenchmark` package. This benchmarking was done on a 2017 MacBook
Air, with a 1.8 GHz Intel Core i5 CPU and 8 GB of memory.

Linear regression
=================

I test our speed in estimating coefficients, standard errors, and doing
inference on four different datasets (500 and 5000 observations; 5 and
50 covariates) and across several different specifications. Below I
preview the results comparing `lm_robust()` to base R for fitting
coefficients and a commonly used package for robust standard errors,
such as the `sandwich` package. In the two largest datasets, our method
is almost always faster and at worst is the same as base R, and only
with classical standard errors. When it comes to the biggest gains,
using `lm_robust()` to get HC2 or Stata-like cluster-robust standard
errors will roughly halve your waiting time. If you want CR2 standard
errors, `lm_robust()` can reduce your run time by a factor of 10!

<table>
<thead>
<tr class="header">
<th>N. Obs</th>
<th>N. Coefs</th>
<th>Estimator</th>
<th>Classical SEs</th>
<th>HC2 SEs</th>
<th>Stata clustered SEs</th>
<th>CR2 SEs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>500</td>
<td>5</td>
<td><code>estimatr::lm_robust()</code></td>
<td>7.9</td>
<td>7.9</td>
<td>7.6</td>
<td><strong>10.6</strong></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>base + sandwich/clubSandwich</td>
<td><strong>2.3</strong></td>
<td><strong>5</strong></td>
<td><strong>6.7</strong></td>
<td>45.9</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>5000</td>
<td>5</td>
<td><code>estimatr::lm_robust()</code></td>
<td>18.7</td>
<td><strong>18.8</strong></td>
<td><strong>17.8</strong></td>
<td><strong>317</strong></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>base + sandwich/clubSandwich</td>
<td><strong>6.4</strong></td>
<td>26</td>
<td>45.9</td>
<td>2121.6</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>500</td>
<td>50</td>
<td><code>estimatr::lm_robust()</code></td>
<td>24.3</strong></td>
<td><strong>28.7</td>
<td><strong>29.5</strong></td>
<td><strong>269</strong></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>base + sandwich/clubSandwich</td>
<td><strong>17.5</strong></td>
<td>43.9</td>
<td>69.5</td>
<td>404.3</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>5000</td>
<td>50</td>
<td><code>estimatr::lm_robust()</code></td>
<td><strong>80.8</strong></td>
<td><strong>111.6</strong></td>
<td><strong>90.5</strong></td>
<td><strong>8464</strong></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>base + sandwich/clubSandwich</td>
<td>88.5</td>
<td>287</td>
<td>480.7</td>
<td>2.510^{4}</td>
</tr>
</tbody>
</table>

Instrumental variables regression
=================================

<table>
<thead>
<tr class="header">
<th>N. Obs</th>
<th>N. Coefs</th>
<th>Estimator</th>
<th>Classical SEs</th>
<th>HC0 SEs</th>
<th>CR2 SEs</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>500</td>
<td>5</td>
<td><code>estimatr::iv_robust()</code></td>
<td><strong>8.2</strong></td>
<td><strong>8.9</strong></td>
<td><strong>11</strong></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>AER + ivpack/clubSandwich</td>
<td>11.9</td>
<td>10.1</td>
<td>49.9</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>5000</td>
<td>5</td>
<td><code>estimatr::lm_robust()</code></td>
<td>17.8</td>
<td><strong>18.9</strong></td>
<td><strong>156.9</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>AER + ivpack/clubSandwich</td>
<td><strong>15.7</strong></td>
<td>22.6</td>
<td>1814.1</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>500</td>
<td>50</td>
<td><code>estimatr::lm_robust()</code></td>
<td><strong>25.8</strong></td>
<td><strong>26.1</strong></td>
<td><strong>80.9</strong></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>AER + ivpack/clubSandwich</td>
<td>46.2</td>
<td>51.8</td>
<td>310.3</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>5000</td>
<td>50</td>
<td><code>estimatr::lm_robust()</code></td>
<td><strong>85.4</strong></td>
<td><strong>93.9</strong></td>
<td><strong>2594.4</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td>AER + ivpack/clubSandwich</td>
<td>144.7</td>
<td>316.4</td>
<td>1.610^{4}</td>
<td></td>
</tr>
</tbody>
</table>

Code that generated these data
==============================

To see the exact comparisons, see below.

    library(estimatr)
    library(microbenchmark)
    # Create some data sets of different sizes for testing below
    set.seed(42)
    data_size <- expand.grid(list(ns = c(500, 5000), ps = c(5, 50)))
    data_list <- lapply(
      1:nrow(data_size), 
      function(i) {
        n <- data_size$ns[i]
        p <- data_size$ps[i]
        y <- rnorm(n)
        X <- matrix(rnorm(n*p), n, p)
        return(data.frame(y, X))
      }
    )

First, we can look at the classical standard errors case. We do a few more computations than `summary.lm` does, and have a bit more overhead.

    test_base <- lapply(data_list, function(dat) {
      mbo <- summary(microbenchmark(
        'lm_robust' = lm_robust(y ~ ., data = dat, se_type = "classical"),
        'base' = summary(lm(y ~ ., data = dat)),
        times = 200L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

The following table has the median time in milliseconds across 50 runs
of each estimator for each of the different data sets.

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">lm_robust</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">24</td>
<td align="right">81</td>
</tr>
<tr class="even">
<td align="left">base</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">18</td>
<td align="right">88</td>
</tr>
</tbody>
</table>

However, the real speed gains come with robust standard errors. Let's
compare `lm_robust` to getting "HC2" standard errors and doing inference
using them from the `coeftest` and `sandwich` packages.

    library(sandwich)
    library(lmtest)

    test_rob <- lapply(data_list, function(dat) {
      mbo <- summary(microbenchmark(
        'lm_robust' = lm_robust(y ~ ., data = dat, se_type = "HC2"),
        'lm + coeftest + sandwich' = {
          lmo <- lm(y ~ ., data = dat)
          coeftest(lmo, vcov = vcovHC(lmo, type = "HC2"))
        },
        times = 200L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">lm_robust</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">29</td>
<td align="right">112</td>
</tr>
<tr class="even">
<td align="left">lm + coeftest + sandwich</td>
<td align="right">5</td>
<td align="right">26</td>
<td align="right">44</td>
<td align="right">287</td>
</tr>
</tbody>
</table>

What about with Stata's clustered standard errors using `tapply` and
`sandwich`?

    # Commonly used function attributed mostly to M. Arai replicating Stata 
    # clustered SEs in R using sandwich and lmtest packages
    cluster_robust_se <- function(model, cluster){
      M <- length(unique(cluster))
      N <- length(cluster)
      K <- model$rank
      dfc <- (M/(M - 1)) * ((N - 1)/(N - K))
      uj <- apply(estfun(model), 2, function(x) tapply(x, cluster, sum));
      rcse.cov <- dfc * sandwich(model, meat = crossprod(uj)/N)
      rcse.se <- coeftest(model, rcse.cov)
      return(list(rcse.cov, rcse.se))
    }

    test_cl <- lapply(data_list, function(dat) {
      cluster <- sample(nrow(dat)/5, size = nrow(dat), replace = TRUE)
      mbo <- summary(microbenchmark(
        'lm_robust' = lm_robust(
          y ~ ., 
          data = dat, 
          clusters = cluster, 
          se_type = "stata"
        ),
        'lm + coeftest + sandwich' = {
          lmo <- lm(y ~ ., data = dat)
          cluster_robust_se(lmo, cluster)
        },
        times = 200L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">lm_robust</td>
<td align="right">8</td>
<td align="right">18</td>
<td align="right">30</td>
<td align="right">90</td>
</tr>
<tr class="even">
<td align="left">lm + coeftest + sandwich</td>
<td align="right">7</td>
<td align="right">46</td>
<td align="right">70</td>
<td align="right">481</td>
</tr>
</tbody>
</table>

The original authors who came up with a generalized version of the CR2
errors and accompanying Satterthwaite-like corrected degrees of freedom
have their own package,
[`clubSandwich`](https://github.com/jepusto/clubSandwich), that provides
estimators for many methods. We show here how much faster our
implementation is for simple linear regression.

    library(clubSandwich)

    test_cr2 <- lapply(data_list, function(dat) {
      cluster <- sample(nrow(dat)/5, size = nrow(dat), replace = TRUE)
      mbo <- summary(microbenchmark(
        'lm_robust' = lm_robust(
          y ~ ., 
          data = dat,
          clusters = cluster, 
          se_type = "CR2"
        ),
        'lm + clubSandwich' = {
          lmo <- lm(y ~ ., data = dat)
          coef_test(lmo, vcov = vcovCR(lmo, cluster = cluster, type = "CR2"))
        },
        times = 50L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

    knitr::kable(create_tab(test_cr2), col.names = col_names)

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">lm_robust</td>
<td align="right">11</td>
<td align="right">317</td>
<td align="right">269</td>
<td align="right">8464</td>
</tr>
<tr class="even">
<td align="left">lm + clubSandwich</td>
<td align="right">46</td>
<td align="right">2122</td>
<td align="right">404</td>
<td align="right">25266</td>
</tr>
</tbody>
</table>

What about for instrumental variables?

    library(AER)
    library(ivpack)
    library(clubSandwich)

    test_iv <- lapply(data_list, function(dat) {
      form <- as.formula(paste0(
        "y ~ ",
        paste(names(dat)[substr(names(dat), 1, 1) == "X"], collapse = " + "),
        " | ",
        paste(names(dat)[substr(names(dat), 1, 1) == "Z"], collapse = " + ")
      ))
      mbo <- summary(microbenchmark(
        'iv_robust' = iv_robust(
          form, 
          data = dat,
          se_type = "classical"
        ),
        'AER::ivreg' = {
          ivo <- summary(ivreg(form, data = dat))
        },
        times = 200L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

    knitr::kable(create_tab(test_iv), col.names = col_names)

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">iv_robust</td>
<td align="right">8</td>
<td align="right">18</td>
<td align="right">26</td>
<td align="right">85</td>
</tr>
<tr class="even">
<td align="left">AER::ivreg</td>
<td align="right">12</td>
<td align="right">16</td>
<td align="right">46</td>
<td align="right">145</td>
</tr>
</tbody>
</table>

    test_iv_rob <- lapply(data_list, function(dat) {
      form <- as.formula(paste0(
        "y ~ ",
        paste(names(dat)[substr(names(dat), 1, 1) == "X"], collapse = " + "),
        " | ",
        paste(names(dat)[substr(names(dat), 1, 1) == "Z"], collapse = " + ")
      ))
      mbo <- summary(microbenchmark(
        'iv_robust' = iv_robust(
          form, 
          data = dat,
          se_type = "HC0"
        ),
        'AER::ivreg + ivpack::robust.se' = {
          ivo <- robust.se(ivreg(form, data = dat))
        },
        times = 200L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

    knitr::kable(create_tab(test_iv_rob), col.names = col_names)

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">iv_robust</td>
<td align="right">9</td>
<td align="right">19</td>
<td align="right">26</td>
<td align="right">94</td>
</tr>
<tr class="even">
<td align="left">AER::ivreg + ivpack::robust.se</td>
<td align="right">10</td>
<td align="right">23</td>
<td align="right">52</td>
<td align="right">316</td>
</tr>
</tbody>
</table>

    test_iv_cl <- lapply(data_list, function(dat) {
      cluster <- sample(nrow(dat)/5, size = nrow(dat), replace = TRUE)
      form <- as.formula(paste0(
        "y ~ ",
        paste(names(dat)[substr(names(dat), 1, 1) == "X"], collapse = " + "),
        " | ",
        paste(names(dat)[substr(names(dat), 1, 1) == "Z"], collapse = " + ")
      ))
      mbo <- summary(microbenchmark(
        'iv_robust' = iv_robust(
          form, 
          data = dat,
          clusters = cluster,
          se_type = "CR2"
        ),
        'AER::ivreg + clubSandwich' = {
          ivo <- clubSandwich::coef_test(ivreg(form, data = dat), cluster = cluster, vcov = "CR2")
        },
        times = 50L
      ),
      unit = "ms")
      return(mbo[, c("expr", "median")])
    })

    knitr::kable(create_tab(test_iv_cl), col.names = col_names)

<table>
<thead>
<tr class="header">
<th align="left">Estimator</th>
<th align="right">N=500, P=5</th>
<th align="right">N=500, P=50</th>
<th align="right">N=5000, P=5</th>
<th align="right">N=500, P=50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">iv_robust</td>
<td align="right">11</td>
<td align="right">157</td>
<td align="right">81</td>
<td align="right">2594</td>
</tr>
<tr class="even">
<td align="left">AER::ivreg + clubSandwich</td>
<td align="right">50</td>
<td align="right">1814</td>
<td align="right">310</td>
<td align="right">15589</td>
</tr>
</tbody>
</table>

    sessionInfo()
    #> R version 3.5.0 (2018-04-23)
    #> Platform: x86_64-apple-darwin15.6.0 (64-bit)
    #> Running under: macOS High Sierra 10.13.3
    #> 
    #> Matrix products: default
    #> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
    #> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
    #> 
    #> locale:
    #> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    #> 
    #> attached base packages:
    #> [1] stats     graphics  grDevices utils     datasets  methods   base     
    #> 
    #> other attached packages:
    #>  [1] clubSandwich_0.3.2      ivpack_1.2             
    #>  [3] AER_1.2-5               survival_2.41-3        
    #>  [5] sandwich_2.4-0          lmtest_0.9-36          
    #>  [7] zoo_1.8-1               car_3.0-0              
    #>  [9] carData_3.0-1           RcppArmadillo_0.8.500.0
    #> [11] RcppEigen_0.3.3.4.0     microbenchmark_1.4-4   
    #> [13] estimatr_0.8.0         
    #> 
    #> loaded via a namespace (and not attached):
    #>  [1] zip_1.0.0         Rcpp_0.12.17      highr_0.6        
    #>  [4] compiler_3.5.0    pillar_1.2.3      cellranger_1.1.0 
    #>  [7] forcats_0.3.0     tools_3.5.0       digest_0.6.15    
    #> [10] evaluate_0.10.1   tibble_1.4.2      lattice_0.20-35  
    #> [13] texreg_1.36.23    rlang_0.2.1       openxlsx_4.1.0   
    #> [16] Matrix_1.2-14     curl_3.2          yaml_2.1.19      
    #> [19] haven_1.1.1       rio_0.5.10        stringr_1.3.1    
    #> [22] knitr_1.20        rprojroot_1.3-2   grid_3.5.0       
    #> [25] data.table_1.11.4 readxl_1.1.0      foreign_0.8-70   
    #> [28] rmarkdown_1.9     Formula_1.2-3     magrittr_1.5     
    #> [31] codetools_0.2-15  splines_3.5.0     backports_1.1.2  
    #> [34] htmltools_0.3.6   abind_1.4-5       stringi_1.2.2
