# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ht_covar_partial <- function(y1, y0, p10, p1, p0) {
    .Call(`_estimatr_ht_covar_partial`, y1, y0, p10, p1, p0)
}

ht_var_partial <- function(y, p) {
    .Call(`_estimatr_ht_var_partial`, y, p)
}

AtA <- function(A) {
    .Call(`_estimatr_AtA`, A)
}

lm_solver <- function(Xfull, y, Xunweighted, weight, weight_mean, cluster, J, ci, type, which_covs, try_cholesky) {
    .Call(`_estimatr_lm_solver`, Xfull, y, Xunweighted, weight, weight_mean, cluster, J, ci, type, which_covs, try_cholesky)
}

