# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ht_var <- function(p1p2, p1, p2, y1, y2) {
    .Call(`_estimatr_ht_var`, p1p2, p1, p2, y1, y2)
}

ht_var_total <- function(y, p) {
    .Call(`_estimatr_ht_var_total`, y, p)
}

ht_var_total2 <- function(y, p) {
    .Call(`_estimatr_ht_var_total2`, y, p)
}

ht_covar_total <- function(y0, y1, p00, p11, pj) {
    .Call(`_estimatr_ht_covar_total`, y0, y1, p00, p11, pj)
}

gen_pr_mat_complete <- function(prs) {
    .Call(`_estimatr_gen_pr_mat_complete`, prs)
}

ht_var_total_clusters <- function(y, ps, cluster) {
    .Call(`_estimatr_ht_var_total_clusters`, y, ps, cluster)
}

mult_diag <- function(x, d) {
    .Call(`_estimatr_mult_diag`, x, d)
}

mat_sqrt_inv <- function(X) {
    .Call(`_estimatr_mat_sqrt_inv`, X)
}

lm_robust_helper <- function(y, X, cluster, ci, type, which_covs) {
    .Call(`_estimatr_lm_robust_helper`, y, X, cluster, ci, type, which_covs)
}

