# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ht_covar_partial <- function(y1, y0, p10, p1, p0) {
    .Call(`_estimatr_ht_covar_partial`, y1, y0, p10, p1, p0)
}

ht_var_partial <- function(y, p) {
    .Call(`_estimatr_ht_var_partial`, y, p)
}

demeanMat <- function(Y, X, Zmat, fes, weights, has_int, eps) {
    .Call(`_estimatr_demeanMat`, Y, X, Zmat, fes, weights, has_int, eps)
}

AtA <- function(A) {
    .Call(`_estimatr_AtA`, A)
}

Kr <- function(A, B) {
    .Call(`_estimatr_Kr`, A, B)
}

lm_solver <- function(X, y, try_cholesky) {
    .Call(`_estimatr_lm_solver`, X, y, try_cholesky)
}

lm_variance <- function(X, Xunweighted, XtX_inv, ei, weight_mean, cluster, J, ci, se_type, which_covs, fe_rank) {
    .Call(`_estimatr_lm_variance`, X, Xunweighted, XtX_inv, ei, weight_mean, cluster, J, ci, se_type, which_covs, fe_rank)
}

naomitwhy <- function(df, recursive_subset) {
    .Call(`_estimatr_naomitwhy`, df, recursive_subset)
}

